### ISSUE TITLE
Does jennifer run the branch head commit or the merge commit?

### ISSUE THREAD

**Issue by alikhajeh1** [percolate/jennifer#2]
Sometimes the branch head commit passes all of the tests, but breaks some of the tests when it's merged into master. Does jennifer run the build against the merge commit? If so, it will inform users that their branch will break the build once it's merged, so they should probably merge master into their branch and make sure all the tests pass.

**Comment by jamesob** [comment]
Jennifer doesn't have or enforce any opinions about what a branch is merged with before it's tested. 

Personally, I've configured the PR job template (and thus all subsequent jennifer-managed jobs) to merge master into the branch being tested. You can do this by modifying the `Merge before build` option in your PR job template configuration; jennifer doesn't know about this and will work fine either way.
